"""users table

Revision ID: 2b3833e40274
Revises: 58c6b0d1cc6a
Create Date: 2024-08-20 05:31:04.442173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3833e40274'
down_revision = '58c6b0d1cc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index('ix_wishlist_timestamp')
        batch_op.drop_index('ix_wishlist_user_id')

    op.drop_table('wishlist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=False),
    sa.Column('body', sa.VARCHAR(length=500), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_index('ix_wishlist_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_wishlist_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
