"""wishlists table

Revision ID: 58c6b0d1cc6a
Revises: e06af66ae7a2
Create Date: 2024-08-20 04:57:51.850529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c6b0d1cc6a'
down_revision = 'e06af66ae7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_timestamp'))

    op.drop_table('wishlist')
    # ### end Alembic commands ###
